### ISSUE TITLE
Test new bigoli firmware

### ISSUE THREAD

**Issue by chsahit** [RoboJackets/roboracing-firmware#2]
We need to reasonably version control the mbed firmware and also start testing it on hardware

- Test a P controller on steering
- Tune PD control on motor output
- Test I/O between MBED firmware and ROS node on the NUC

**Comment by btdubs** [comment]
The code is done minus some cleanup after competition. It also now has ethernet connection instead of serial.

**Comment by btdubs** [comment]
Added a note to self here, I think the Bigoli firmware has a similar problem to Sedani, where we don't check for a terminating character. This should be fixed before merging Ethernet (bigoli-firmware) to master

**Comment by jspall0327** [comment]
Will the note ^^ for this be handled by the new wrapper? Aka close this issue.

**Comment by jspall0327** [comment]
I agree, that's what we should do. I just think issue #15 handles the comment about terminating character and the original intention of the issue was resolved with bigoli comp code merged earlier during this semester. Just think the issue is outdated.

**Comment by btdubs** [comment]
Closing this because RIP Bigoli. That pasta will always have a special place in our hearts.
