### ISSUE TITLE
Servo output randomly full negative

### ISSUE THREAD

**Issue by jspall0327** [RoboJackets/roboracing-firmware#21]
Occurred during testing. Don't really know when it occurs, but it obviously should be corrected.

**Comment by btdubs** [comment]
Is this for the steering servo suddenly trying to turn or the car driving full backwards all of a sudden? I don't remember the steering servo doing odd things from testing day.

**Comment by jspall0327** [comment]
Serial output of the "measured steering" angle, which should just be the value of the desired steering angle, would show this. Don't think the servo would actually move.

**Comment by jspall0327** [comment]
#24 Should handle this issue

**Comment by btdubs** [comment]
For future clarity, https://github.com/RoboJackets/roboracing-firmware/commit/ba7675527afc4c349cc017fb7234a1b8d624f628 solves this. It was a bug with using an unsigned int but the number going negative.
