### ISSUE TITLE
IMU 

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-firmware#5]
Our IMU needs to be debugged. Does it work? Can we get better data out of it?

**Comment by btdubs** [comment]
[razor_imu](https://github.com/RoboJackets/roboracing-firmware/tree/razor_imu) repo holds code for this that Luis has worked on. Should be able to merge soon tm.

**Comment by jspall0327** [comment]
Can this be merged?

**Comment by btdubs** [comment]
Luis last worked on it and said there were still one or two things to finish. We haven't had time to look at it and see what needs finishing. Should not be much to finish, but just not a priority right now, so no not ready to merge.
